### ISSUE TITLE
checker program is not reimported when updating a task

### ISSUE THREAD

**Issue by CristianCantoro** [cms-dev/cms#970]
**Description:**

`correttore`/`checker` is not reimported when `cmsImportTask -u`

**Steps to reproduce:**
1. Import a task in CMS and attach it to a contest.
2. Modify your checker script.
3. From the task directory, run `cmsMake -c`
4. From the task directory, run `cmsMake -a`
5. From the task directory, run `cmsImportTask [-L italy_yaml] -u -c CONTEST_ID .`

**Expected:**

The new version of `checker` gets uploaded to the contest.

**Actual:** 

The contest is still using the old version of `checker`.

A workaround is deleting the checker and re-uploading it through the admin interface.

### Logs

No relevant logs.

### System Information

**CMS version:** `1.3.1`
**Was CMS installed:** yes
**Using a virtualenv:** no
**Postgres version:** 9.3.18
**Distribution and version:** Ubuntu 16.04.4 LTS (xenial)

**Comment by stefano-maggiolo** [comment]
This might very well be :(

Such a bug is below the threshold for getting a backport, even a non-immediate-release one, given that it was already fixed in master (we refactored that code substantially).

But testing in master made me realize that an independent change broke the update version of the importers, so thank you! I'm going to fix that now.

**Comment by CristianCantoro** [comment]
Just as a sidenote, I'm still experiencing this issue with `cms v1.3.2`. I am not currently in a position where I would be comfortable upgrading my system to `cms v1,4.X` for a number of reasons (including the fact that I am still running Ubuntu 16.04 on the server hosting it. So for the time being, I will keep using the workaround described above, i.e. updating the checker executable through the admin interface.
